replicaCount: 1
image:
  imagePolicy: enabled
  repository: devkrolikowski/swiss-army-knife
  tag: 0.3.0 # {"$imagepolicy": "flux-system:helper:tag"}
  command: 
    - "cmd.sh"
  args: 
    - "cmdarg"
resources:
  limits:
    memory: "1024Mi"
    cpu: "2"
  requests:
    memory: "1024Mi"
    cpu: "1"
ingress:
  enabled: false
volumes:
  enabled: true
  mountPath: 
    - storage:/storage
  type:
    nfs:
      server: lab-storage.lan
      path: /volume1/storagelab
nodeSelector:
  kubernetes.io/arch: arm64