apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "basic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "basic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.image.command }}
          command:
          {{- with .Values.image.command }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.image.args }}
          args:
          {{- with .Values.image.args }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.volumes.enabled }}
          volumeMounts:
            {{- range .Values.volumes.mountPath }}
            {{- $dirmap := regexSplit ":" . -1 }}
            {{- $sub_path := slice $dirmap 0 1 | first }}
            {{- $mount := slice $dirmap  1 | last }}
            {{- if $.Values.volumes.type.pvc }}
            {{- $path := $mount }}
            - mountPath: {{ $mount | default "/var/www" }}
              name: {{ $.Release.Name }}-volume
            {{- else }}
            - mountPath: {{ $mount | default "/var/www" }}
              name: {{ $.Release.Name }}-volume
              subPath: {{ $sub_path }}
            {{- end }}
            {{- end }}
          {{- end}}
          env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range .Values.services }}
            - name: {{ .name }}
              containerPort: {{.targetPort }}
              protocol: TCP
            {{- end }}
          {{- if .Values.startupProbes.enabled }}
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.startupProbes.port | default 80 }}
            failureThreshold: 30
            periodSeconds: 10
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: 10
            periodSeconds: 2
          {{- end }}
      {{- if .Values.livenessProbe }}
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      {{- end }}
      {{ if .Values.image.registrySecret }}
      imagePullSecrets:
      - name: {{ .Values.image.registrySecret }}
      {{ end }}
      nodeSelector:
      {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes.enabled }}
      {{- if .Values.volumes.type.pvc }}
      {{- $ownership := regexSplit ":" .Values.volumes.ownership -1 }}
      {{- $gid := slice $ownership 0 1 | first }}
      securityContext:
        fsGroup: {{ $gid | default 0 }}
      {{- end}}
      volumes:
        - name: {{ .Release.Name }}-volume
          {{- if .Values.volumes.type.nfs }}
          nfs:
            server: {{ .Values.volumes.type.nfs.server }}
            {{- if .Values.volumes.rootDir }}
            path: {{ .Values.volumes.type.nfs.path }}/{{ .Values.volumes.rootDir }}
            {{- else }}
            path: {{ .Values.volumes.type.nfs.path }}/{{ .Release.Name }}
            {{- end }}
            readOnly: false
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
          {{- end }} 
    {{- end }}