{{- if .Values.image.imagePolicy -}}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: {{ .Release.Name }}
  namespace: flux-system
spec:
  image: {{ .Values.image.repository }}
  {{ if .Values.image.registrySecret }}
  secretRef:
    name: {{ .Values.image.registrySecret }}
  {{- end }}
  interval: 1m0s
{{- end -}}