{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.hosts }}
{{- $subdomain := .name | splitList "." | first -}}
{{- $ReleaseName := printf "%s-%s" $.Release.Name $subdomain -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ReleaseName }}
  namespace: {{ $.Release.Namespace }}
  {{- if $.Values.ingress.ssl }}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  {{- end }}
spec:
  rules:
    - host: {{ .name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $ReleaseName }}
                port:
                  number: {{ .servicePort }}
  {{- if $.Values.ingress.ssl }}
  tls:
    - secretName: {{ $ReleaseName }}-tls
      hosts:
        - {{ .name }}
  {{- end }}
  {{ printf "\n" }}
  {{- end }}
  {{- end -}}
