{{- if .Values.volumes.enabled -}}
{{- if .Values.volumes.type.nfs -}}
{{- $dirs_to_create := "" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-websitedir"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: "{{ .Release.Name }}-init-websitedir"
          image: gitea.angrybits.pl/kkrolikowski/toolbox:0.0.1
          env:
          - name: WEBSITE_DIRS
            {{- range .Values.volumes.mountPath }}
            {{- $dirmap := regexSplit ":" . -1 -}}
            {{- $dir := slice $dirmap 0 1 | first -}}
            {{- if $.Values.volumes.rootDir -}}
            {{- $dirs_to_create = printf "%s %s/%s/%s" $dirs_to_create "/storage" $.Values.volumes.rootDir $dir }}
            {{- else }}
            {{- $dirs_to_create = printf "%s %s/%s/%s" $dirs_to_create "/storage" $.Release.Name $dir }}
            {{- end }}
            {{- end }}
            value: {{ $dirs_to_create }}
          - name: OWNERSHIP
            value: {{ .Values.volumes.ownership | default "root:root" }}
          volumeMounts:
            - mountPath: /storage
              name: {{ .Release.Name }}-volume
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                if [! -d $(WEBSITE_DIRS) ]; then
                  mkdir -p $(WEBSITE_DIRS); 
                  chown -R $(OWNERSHIP) $(WEBSITE_DIRS);
                fi
      nodeSelector:
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: {{ .Release.Name }}-volume
          nfs:
            server: {{ .Values.volumes.type.nfs.server }}
            path: {{ .Values.volumes.type.nfs.path }}
{{- end }}
{{- end }}
