apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-mattermost"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: curlimages/curl:8.1.1
          env:
          - name: MM_USERNAME
            valueFrom:
              secretKeyRef:
                name: cron-secrets
                key: mm_usernane
          - name: MM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: cron-secrets
                key: mm_bot_token
          - name: MM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: cron-secrets
                key: mm_bot_token
          - name: MM_CHAT
            valueFrom:
              secretKeyRef:
                name: cron-secrets
                key: mm_chat
          - name: APP_NAME
            value: {{ .Release.Name }}
          - name: APP_VERSION
            value: {{ .Values.image.tag }}
          command: ["/usr/bin/curl", "-i"]
          args:
            - >-
                -X POST \
                -H 'Content-Type: application/json' \
                -H 'Authorization: Bearer $(MM_BOT_TOKEN)' \
                -d '{"username": "$(MM_USERNAME)", \
                    "text": ":bulb: Application: $(APP_NAME), version: $(APP_VERSION) was deployed! :tada:"}' \
                $(MM_CHAT)