{{- if .Values.volumes.enabled }}
{{- if hasKey .Values.volumes.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-2repl
  resources:
    requests:
      storage: {{ .Values.volumes.type.pvc.size }}
{{- end }}
{{- end }}
