{{- range .Values.application.services }}
{{- if gt .port 0.0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-svc
  namespace: default
spec:
  {{- if eq .name "http" }}
  type: ClusterIP
  {{- else if eq .name "ssh" }}
  type: LoadBalancer
  {{- else }}
  type: NodePort
  {{- end }}
  ports:
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port | default 80 }}
      {{- if eq .name "ssh" }}
      targetPort: 22
      {{- else }}
      targetPort: {{ .port | default 80 }}
      {{- end }}
  selector:
    app.kubernetes.io/app: {{ $.Release.Name }}
{{- end }}
{{- end }}