{{- $services_count := len .Values.services -}}
{{- if gt $services_count 0 }}
{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-{{ .name }}"
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .type }}
  {{- if .loadBalancerIP }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
  ports:
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .servicePort }}
      targetPort: {{ .targetPort }}
  selector:
    app.kubernetes.io/app: {{ $.Release.Name }}
{{- end }}
{{- end }}
